name: Problem report
description: Create a report to help us improve
labels: [problem]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Before submitting:
        - You read the [FAQ](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/EN/EN_faq.md)  
  - type: textarea
    id: what_happend
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expect_to_happen
    attributes:
      label: What did you expect to happen?
      placeholder: I expected that ...
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce it (minimal and precise)
      placeholder: First do this, than this..
    validations:
      required: false
  - type: input
    id: adapter_version
    attributes:
      label: Adapter version
      placeholder: 2.3.0
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
    validations:
      required: false
